fun main(){
    println("Student Enrollment No.:")
    var a= readLine()?.toIntOrNull()
    println("Student Name:")
    var b= readLine()
    println("Student Branch:")
    var c= readLine()
    println("Student Class:")
    var d= readLine()
    println("Student Batch:")
    var e= readLine()
    println("Student Collage Name:")
    var f= readLine()
    println("Student University Name:")
    var s= readLine()
    println("Student Age:")
    var i= readLine()?.toInt()

    println("Student's Data---------------")
    println("Enrollment No.:$a")
    println("Name:$b")
    println("Branch:$c")
    println("Class:$d")
    println("Batch:$e")
    println("Collage Name:$f")
    println("University Name:$s")
    println(" Age:$i")

}